name: Altis Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build-test:
    strategy:
      matrix:
        php: ['7.4']
      fail-fast: false
    name: Altis on PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          version: 1 # Composer 1
          ssh_key: ${{ secrets.ssh_key }}
          ssh_key_pub: ${{ secrets.ssh_key_pub }}

      - name: Start the containers
        shell: 'script -q -e -c "bash {0}"'
        run: |
          composer server start
